name: Test Blogger Bot
on:
  workflow_dispatch: # လူကိုယ်တိုင် ခလုတ်နှိပ်ပြီး မောင်းနှင်ရန်
  schedule:
    - cron: '*/5 * * * *' # ၅ မိနစ်တစ်ခါ Website ကို စစ်ဆေးရန်

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install requests
      - name: Run Bot
        env:
          BLOG_ID: ${{ secrets.BLOG_ID }}
          BLOGGER_API_KEY: ${{ secrets.BLOGGER_API_KEY }}
        run: python bot.py
